### ISSUE TITLE
File Extension

### ISSUE THREAD

**Issue by navierula** [jwkeepers/intro-data-capstone-musclehub#1]
If you worked in a Jupyter notebook, be sure to use `.ipynb` instead of `.py` as your file extension.

https://github.com/jwkeepers/intro-data-capstone-musclehub/blob/8fc89e72266dffbcb37ff1ee0e3df21e9d9ad0ad/Joe_keeper_MuscleHub/joe_keepers_musclehub_proj.py#L1

**Comment by jwkeepers** [comment]
Uploaded the file with th correct extension: note code academy instructions give the wrong extension.  Thanks for the comment
