### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [jwkeepers/intro-data-capstone-musclehub#2]
**Presentation and Analysis Document (4/4)**
✓ Document in PDF format
✓ Overview slide to state the objective of the analysis
✓ Data observations slides using matplotlib plots
✓ Slide for hypothesis testing and results
✓ Slide to share the findings from qualitative data
✓ Recommendation / Conclusion slide

**Code Accuracy (4/4)**
Accurate Python code for every question in the project for:
✓ Matplotlib plots
✓ Data analysis
✓ Hypothesis testing

**Understanding Hypothesis Testing (4/4)**
✓ State the hypothesis
✓ Run hypothesis testing and state the results
✓ Based on the results, accept/reject the hypothesis
✓ Interpret the hypothesis outcome and connect to the objective of the analysis

**Ability to Interpret the Objective & Outcome of the Analysis in Business Context (4/4)**
✓ Objective clearly states the business reason for the analysis
✓ Findings are interpreted accurately and are summarized in Recommendation / Conclusion. It addresses the questions raised in the objective of the analysis

---

Great job on this project! I enjoyed reading through your analyses in the slides. Next time, be sure to include code as evidence.

**Comment by jwkeepers** [comment]
Please elaborate, code in a presentation?  I would think only for the most technical of audiences.  The audience would be data scientist, who are learning how to approach a problems such as this.  I assumed, perhaps wrongly, the presentation was for management who were not particularly tech savy, but needed the results of such a study.  Thank you for your comments.

**Comment by navierula** [comment]
Hi @jwkeepers! You're right, that could definitely be the case. Overall, you did very well on your project. Since the project highlighted your technical work, I thought it would interesting to highlight code if you were presenting it to a technical audience. I understand your point, though, so thanks for sharing it!
